const data = {
  products: [
    {
      _id: '1',
      name: 'Snickers',
      category: 'Chocolate',
      image: '/images/p1.jpg',
      price: 60,
      countInStock: 10,
      brand: 'snickers',
      rating: 4.5,
      numReviews: 10,
      description: 'It is a description',
    },
    {
      _id: '2',
      name: 'Kitkat',
      category: 'Chocolate',
      image: '/images/p2.jpg',
      price: 185,
      countInStock: 20,
      brand: 'Nestlé',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Apple',
      category: 'Fruits',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Non-brand',
      rating: 4.8,
      numReviews: 17,
      description: 'Weight: 1 kg',
    },
    {
      _id: '4',
      name: 'Guava',
      category: 'Fruits',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 15,
      brand: 'Local',
      rating: 4.5,
      numReviews: 14,
      description: 'Weight: 1kg',
    },
    {
      _id: '5',
      name: 'Mango',
      category: 'Fruits',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Local',
      rating: 4.5,
      numReviews: 10,
      description: 'Weight: 1kg',
    },
    {
      _id: '6',
      name: 'Dairy Milk Silk',
      category: 'Chocolate',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Cadberry',
      rating: 4.5,
      numReviews: 15,
      description: 'Chocolate choco',
    },
  ],
};
export default data;
